//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterContable.ServiceContable {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCuenta", Namespace="http://schemas.datacontract.org/2004/07/SistemaContable")]
    [System.SerializableAttribute()]
    public partial class EstadoCuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteIdField, value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceContable.IContabilidadService")]
    public interface IContabilidadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContabilidadService/RegistrarPago", ReplyAction="http://tempuri.org/IContabilidadService/RegistrarPagoResponse")]
        AdapterContable.ServiceContable.EstadoCuenta RegistrarPago(string clienteId, int monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContabilidadService/RegistrarPago", ReplyAction="http://tempuri.org/IContabilidadService/RegistrarPagoResponse")]
        System.Threading.Tasks.Task<AdapterContable.ServiceContable.EstadoCuenta> RegistrarPagoAsync(string clienteId, int monto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContabilidadServiceChannel : AdapterContable.ServiceContable.IContabilidadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContabilidadServiceClient : System.ServiceModel.ClientBase<AdapterContable.ServiceContable.IContabilidadService>, AdapterContable.ServiceContable.IContabilidadService {
        
        public ContabilidadServiceClient() {
        }
        
        public ContabilidadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContabilidadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdapterContable.ServiceContable.EstadoCuenta RegistrarPago(string clienteId, int monto) {
            return base.Channel.RegistrarPago(clienteId, monto);
        }
        
        public System.Threading.Tasks.Task<AdapterContable.ServiceContable.EstadoCuenta> RegistrarPagoAsync(string clienteId, int monto) {
            return base.Channel.RegistrarPagoAsync(clienteId, monto);
        }
    }
}
